'use client';
import { useEffect, useRef, useState } from 'react';
import { Headphones, Upload, Link2, Play, Pause, RotateCcw, ChevronLeft, ChevronRight, Check, FileText, ArrowUpRight } from 'lucide-react';
import { Tabs, TabsList, TabsTrigger, TabsContent } from '@/components/ui/tabs';
import { Select, SelectTrigger, SelectValue, SelectContent, SelectItem } from '@/components/ui/select';
import { Progress } from '@/components/ui/progress';
import { parseSubtitles, normalize, type Sentence } from '@/lib/subtitles';

export default function Home() {
 const [src,setSrc]=useState(''), [name,setName]=useState('尚未导入素材'), [url,setUrl]=useState(''), [subUrl,setSubUrl]=useState('');
 const [sentences,setSentences]=useState<Sentence[]>([]),[index,setIndex]=useState(0),[drafts,setDrafts]=useState<Record<number,string>>({}),[checked,setChecked]=useState<Record<number,boolean>>({});
 const [message,setMessage]=useState(''),[busy,setBusy]=useState(false),[playing,setPlaying]=useState(false),[round,setRound]=useState(0),[rate,setRate]=useState('1'),[subtitleName,setSubtitleName]=useState(''),[ready,setReady]=useState(false);
 const video=useRef<HTMLVideoElement>(null), run=useRef(0), timer=useRef<ReturnType<typeof setTimeout>|null>(null), fileUrl=useRef(''), input=useRef<HTMLTextAreaElement>(null);
 const sentence=sentences[index],answer=drafts[index]||'',revealed=checked[index]||false;
 function stop(){run.current++;if(timer.current)clearTimeout(timer.current);video.current?.pause();setPlaying(false);}
 useEffect(()=>()=>{run.current++;if(timer.current)clearTimeout(timer.current);if(fileUrl.current)URL.revokeObjectURL(fileUrl.current);},[]);
 function loadSubs(text:string,label:string){const parsed=parseSubtitles(text);if(!parsed.length)throw Error('没有找到有效的时间轴，请使用 SRT 或 VTT 字幕。');stop();setSentences(parsed);setSubtitleName(label);setIndex(0);setDrafts({});setChecked({});setRound(0);setMessage(`已整理为 ${parsed.length} 个听写片段，可在下方微调时间。`);}
 function setMedia(value:string,label:string){stop();if(fileUrl.current)URL.revokeObjectURL(fileUrl.current);fileUrl.current=value.startsWith('blob:')?value:'';setSrc(value);setName(label);setReady(false);setRound(0);setDrafts({});setChecked({});}
 async function importUrls(){setBusy(true);setMessage('');try{const u=new URL(url);if(!['http:','https:'].includes(u.protocol))throw Error('请输入 http 或 https 视频直链。');if(/(^|\.)pan\.baidu\.com$/.test(u.hostname))throw Error('请先从百度网盘下载视频与字幕，再在「本地文件」导入。当前版本尚未接入网盘授权读取。');let subs='';if(subUrl.trim()){const su=new URL(subUrl);if(!['https:','http:'].includes(su.protocol))throw Error('字幕地址格式不正确。');const res=await fetch(su,{signal:AbortSignal.timeout(15000)});if(!res.ok)throw Error('字幕链接无法访问。');subs=await res.text();if(!parseSubtitles(subs).length)throw Error('链接内容不是有效的 SRT / VTT 字幕。');}setMedia(u.href,decodeURIComponent(u.pathname.split('/').pop()||'链接视频'));if(subs)loadSubs(subs,'链接字幕');else{setSentences([]);setSubtitleName('');setMessage('视频地址已载入，请在本地文件页选择配套字幕。');}}catch(e){setMessage(e instanceof Error?e.message:'导入失败，请检查链接及跨域访问权限。');}finally{setBusy(false);}}
 async function playTwice(){const v=video.current;if(!v||!sentence||!ready)return;if(Number.isFinite(v.duration)&&sentence.end>v.duration){setMessage('这句的结束时间超过视频时长，请检查字幕是否配套或微调时间。');return;}stop();const id=run.current;setMessage('');setPlaying(true);const clip={...sentence};
 const playRound=async(n:number)=>{if(id!==run.current)return;setRound(n);try{v.currentTime=clip.start;v.playbackRate=Number(rate);await v.play();if(id!==run.current){v.pause();return;}const monitor=()=>{if(id!==run.current)return;if(v.currentTime>=clip.end||v.ended){v.pause();if(n===1)timer.current=setTimeout(()=>void playRound(2),1000);else{setPlaying(false);setMessage('两遍播放完成，写下你听到的句子。');input.current?.focus();}}else timer.current=setTimeout(monitor,20);};monitor();}catch{if(id===run.current){setPlaying(false);setMessage('视频无法播放，请确认文件格式或直链有效。');}}};void playRound(1);}
 function go(i:number){stop();setIndex(i);setRound(0);setMessage('');}
 function boundary(key:'start'|'end',value:string){stop();const n=Number(value);if(!sentence||!Number.isFinite(n)||n<0)return;const edited={...sentence,[key]:n};if(edited.end<=edited.start)return;setSentences(prev=>prev.map((s,i)=>i===index?edited:s));}
 const time=(s:number)=>`${Math.floor(s/60).toString().padStart(2,'0')}:${(s%60).toFixed(1).padStart(4,'0')}`;
 return <main>
 <header className="topbar"><a className="brand" href="/"><span className="brand-icon"><Headphones size={23}/></span>听句 <span className="brand-en">Listen, then write.</span></a><span className="private-label">你的英语听写练习室</span></header>
 <div className="workspace"><section className="intro"><div><div className="eyebrow">LISTENING STUDIO</div><h1>听清一句，写下一句。</h1><p>每句两遍，把听懂变成真正掌握。</p></div><span className="step-pill">01 导入素材 <span>—</span> 02 逐句听写</span></section>
 <div className="columns"><aside className="import-panel"><div className="panel-heading"><span className="number">01</span><h2>导入听力素材</h2></div>
 <Tabs defaultValue="file"><TabsList className="w-full"><TabsTrigger value="file"><Upload/>本地文件</TabsTrigger><TabsTrigger value="url"><Link2/>链接导入</TabsTrigger></TabsList><TabsContent value="file"><label className="drop-area"><Upload size={27}/><strong>{src?name:'选择视频或音频'}</strong><span>MP4、WebM、MP3 等浏览器支持的格式</span><input aria-label="选择视频或音频" type="file" accept="video/*,audio/*" onChange={e=>{const f=e.target.files?.[0];if(f){setMedia(URL.createObjectURL(f),f.name);setSentences([]);setSubtitleName('');setMessage('请选择与这份素材配套的字幕。');}}}/></label><label className="subtitle-upload"><FileText size={20}/><span><strong>{subtitleName||'选择配套英文字幕'}</strong><small>SRT / VTT 格式</small></span><span>＋</span><input aria-label="选择字幕" type="file" accept=".srt,.vtt" onChange={async e=>{const f=e.target.files?.[0];if(f)try{loadSubs(await f.text(),f.name);}catch(err){setMessage((err as Error).message);}}}/></label><p className="note">文件只在当前浏览器中读取。刷新页面后需重新导入。</p></TabsContent><TabsContent value="url"><label className="field">视频直链<input value={url} onChange={e=>setUrl(e.target.value)} placeholder="https://…/video.mp4"/></label><label className="field">字幕链接（可选）<input value={subUrl} onChange={e=>setSubUrl(e.target.value)} placeholder="https://…/subtitle.srt"/></label><button className="primary full" disabled={!url.trim()||busy} onClick={importUrls}>{busy?'正在导入…':'载入素材'}<ArrowUpRight size={17}/></button><p className="note">需使用允许访问的视频直链；网页分享链接不等同于视频文件。</p></TabsContent></Tabs>
 <div className="baidu-note"><strong>素材在百度网盘？</strong><p>先下载视频与字幕，再选择本地文件导入。网盘自动读取尚未接入。</p></div>
 <div className="sentence-heading"><h3>句子列表</h3><span>{sentences.length} 句</span></div><div className="sentence-list">{sentences.length?sentences.map((s,i)=><button key={i} className={`sentence-item ${i===index?'selected':''}`} onClick={()=>go(i)}><span className="sentence-index">{String(i+1).padStart(2,'0')}</span><span><strong>第 {i+1} 句</strong><small>{time(s.start)} — {time(s.end)}</small></span>{checked[i]?<Check size={17}/>:<span className="duration">{(s.end-s.start).toFixed(1)}s</span>}</button>):<p className="empty-list">导入字幕后，句子会出现在这里。</p>}</div>
 </aside><section className="practice"><div className="practice-top"><div><div className="eyebrow">NOW PRACTICING</div><h2>{src?name:'从一段喜欢的英语开始'}</h2></div><span className="mode-badge">逐句听写</span></div>
 <div className="video-stage">{src?<video ref={video} src={src} playsInline preload="metadata" onLoadedMetadata={()=>{setReady(true);}} onError={()=>{stop();setReady(false);setMessage('无法读取视频，请检查文件格式、链接有效期或访问权限。');}}/>:<div className="video-empty"><Headphones size={42}/><h3>准备好，专注听。</h3><p>导入视频和字幕，开启第一句听写</p></div>}<span className="video-caption">{sentence?`${time(sentence.start)} — ${time(sentence.end)}`:'视频预览'} · 字幕已隐藏</span></div>
 <div className="playbar"><div className="play-controls"><button aria-label="上一句" className="icon-btn" disabled={!index} onClick={()=>go(index-1)}><ChevronLeft/></button><button className="primary" disabled={!sentence||!ready} onClick={playing?stop:playTwice}>{playing?<Pause size={18}/>:<Play size={18}/>} {playing?'暂停':'播放两遍'}</button><button aria-label="下一句" className="icon-btn" disabled={!sentence||index===sentences.length-1} onClick={()=>go(index+1)}><ChevronRight/></button></div><div className="speed"><span>{round?`第 ${round} / 2 遍`:'每句 2 遍'}</span><Select value={rate} onValueChange={v=>{stop();setRate(v);}}><SelectTrigger aria-label="播放速度"><SelectValue/></SelectTrigger><SelectContent>{['0.5','0.75','1','1.25'].map(v=><SelectItem key={v} value={v}>{v}×</SelectItem>)}</SelectContent></Select></div></div>
 <div className="writing"><div className="writing-heading"><h2><span className="number">02</span> 写下你听到的内容</h2><span>{sentences.length?`${index+1} / ${sentences.length}`:'等待素材'}</span></div><textarea ref={input} aria-label="英语听写内容" value={answer} disabled={!sentence} spellCheck={false} placeholder="Type what you hear…" onChange={e=>{setDrafts({...drafts,[index]:e.target.value});setChecked({...checked,[index]:false});}} onKeyDown={e=>{if((e.ctrlKey||e.metaKey)&&e.key==='Enter'&&answer.trim()){e.preventDefault();setChecked({...checked,[index]:true});}}}/><div className="writing-actions"><span>⌘ / Ctrl + Enter 核对答案</span><button className="primary" disabled={!answer.trim()||!sentence} onClick={()=>setChecked({...checked,[index]:true})}><Check size={17}/>核对答案</button></div>
 {revealed&&sentence&&<div className="answer"><strong>{normalize(answer)===normalize(sentence.text)?'完全正确，继续下一句！':'对照原句，再听一次'}</strong><p>{sentence.text}</p><small>忽略大小写和标点进行整句比对。</small><button className="text-btn" onClick={playTwice}><RotateCcw size={15}/>再听两遍</button></div>}
 <p role="status" className="status">{message}</p>
 {sentence&&<details><summary>微调句子时间</summary><div className="boundaries"><label>开始（秒）<input type="number" min="0" step="0.1" value={sentence.start} onChange={e=>boundary('start',e.target.value)}/></label><label>结束（秒）<input type="number" min="0" step="0.1" value={sentence.end} onChange={e=>boundary('end',e.target.value)}/></label></div><p className="note">按字幕标点合并相邻条目；同一条字幕含多句时暂保留为一个片段。可微调边界，视频本身不会被剪裁。</p></details>}
 </div><footer className="progress-footer"><span>本次已核对 {Object.values(checked).filter(Boolean).length} / {sentences.length} 句</span><Progress aria-label="听写进度" value={sentences.length?Object.values(checked).filter(Boolean).length/sentences.length*100:0}/></footer></section></div>
 <p className="bottom-note">听两遍 · 写下来 · 对照原句 · 再向前一步</p></div></main>;
}
